version: "3.8"

services:
  # PostgreSQL database for local development
  postgres:
    image: postgres:16-alpine
    container_name: personal-site-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-personal_site}
      POSTGRES_USER: ${POSTGRES_USER:-personal_site_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password_change_in_production}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-personal_site_user} -d ${POSTGRES_DB:-personal_site}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - personal-site-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  personal-site-network:
    driver: bridge
